# acl.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Access Control Lists
#
# Auto-generated by install script
# Date: Thu, 11 Jun 2026 03:47:26 +0000
*               @ALL          1
*               @user         8

