<?php
/*
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by config plugin
 * Run for user: jumpstartadmin
 * Date: Wed, 17 Jun 2026 15:12:01 +0000
 */

$conf['title'] = 'JumpStart';
$conf['template'] = 'bootstrap3';
$conf['license'] = '0';
$conf['useacl'] = 1;
$conf['autopasswd'] = 0;
$conf['superuser'] = '@admin';
$conf['plugin']['confightmlok']['use_sure'] = 1;
$conf['plugin']['confightmlok']['use_really_sure'] = 1;
$conf['tpl']['bootstrap3']['bootstrapTheme'] = 'bootswatch';
$conf['tpl']['bootstrap3']['bootswatchTheme'] = 'cyborg';
$conf['tpl']['bootstrap3']['showUserHomeLink'] = 0;
$conf['tpl']['bootstrap3']['showWikiInfo'] = 0;
$conf['tpl']['bootstrap3']['socialShareProviders'] = 'facebook,linkedin,microsoft-teams,pinterest,whatsapp,reddit,twitter,telegram,yammer,google-plus';
