# users.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Userfile
#
# Auto-generated by install script
# Date: Thu, 11 Jun 2026 03:47:26 +0000
#
# Format:
# login:passwordhash:Real Name:email:groups,comma,separated

jumpstartadmin:$1$1VS4aJYN$GNg84h2t5Z1DXIi3GX8zz1:RegretfulCurve:admin@jumpstart.gg:admin,user
limelight:$2y$10$tvu5xaHZ9f2R1u8vT2Xzs.2LImGA0uamMhhgqsBwMLb7TJgNeO90W:LimeLight:lymey3423@gmail.com:user
4800lightbulbs:$2y$10$2SzcUL69E21MSxBeO7xo2ermN1eAmNqv3vt67AjiaKg1bt4BTd6vO:LimeLight:lymey3423@gmail.com:user
awooga_dl:$2y$10$ttCS4SpLZ64eVs49UfvjHusznoZL/hq0r0/Omx.rbpyBPFD8ZppPW:Awooga:awoogadeadlock@gmail.com:user
